### ISSUE TITLE
Problema con los acentos

### ISSUE THREAD

**Issue by JMailloH** [JJ/cloud-computing#1]
Problema con los acentos en las diapositivas.

**Comment by JJ** [comment]
Perdona, no sé si terminé esto. ¿Está solucionado?

**Comment by JMailloH** [comment]
No te sabría decir. Estaba revisando que tenía abierto y me lo he encontrado. No recuerdo ni a que hace referencia exactamente.

**Comment by JJ** [comment]
Creo que está ya solucionado. Tiene otros muchos problemas, pero ese en concreto está solucionado :-)
